### ISSUE TITLE
net core version?

### ISSUE THREAD

**Issue by nukec** [serilog-contrib/serilog-sinks-azuretablestorage#34] opened 2017-04-06 12:58 UTC
This doesn't work with .net core, when i try to install it complains about Edm package not compactible with .net core.

**Comment by nukec** [comment] 2017-04-06 21:14
@adamchester 

> Installing Serilog.Sinks.PeriodicBatching 2.1.0.
> Installing Serilog.Sinks.AzureTableStorage 4.0.0-dev-00082.
> Install-Package : Package Microsoft.Data.OData 5.6.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Data.OData 5.6.4 supports:
>   - net40 (.NETFramework,Version=v4.0)
>   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
>   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
>   - sl4 (Silverlight,Version=v4.0)
> At line:1 char:1
> + Install-Package Serilog.Sinks.AzureTableStorage -Pre
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package Microsoft.Data.Services.Client 5.6.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Data.Services.Client 5.6.4 supports:
>   - net40 (.NETFramework,Version=v4.0)
>   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
>   - sl4 (Silverlight,Version=v4.0)
> At line:1 char:1
> + Install-Package Serilog.Sinks.AzureTableStorage -Pre
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package System.Spatial 5.6.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package System.Spatial 5.6.4 supports:
>   - net40 (.NETFramework,Version=v4.0)
>   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
>   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
>   - sl4 (Silverlight,Version=v4.0)
> At line:1 char:1
> + Install-Package Serilog.Sinks.AzureTableStorage -Pre
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package Microsoft.Data.Edm 5.6.4 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Microsoft.Data.Edm 5.6.4 supports:
>   - net40 (.NETFramework,Version=v4.0)
>   - portable-net40+sl5+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile328)
>   - portable-net45+win8+wp8+wpa81 (.NETPortable,Version=v0.0,Profile=Profile259)
>   - sl4 (Silverlight,Version=v4.0)
> At line:1 char:1
> + Install-Package Serilog.Sinks.AzureTableStorage -Pre
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : One or more packages are incompatible with .NETCoreApp,Version=v1.1.
> At line:1 char:1
> + Install-Package Serilog.Sinks.AzureTableStorage -Pre
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Install-Package : Package restore failed. Rolling back package changes for 'Gym.IdentityServer'.
> At line:1 char:1
> + Install-Package Serilog.Sinks.AzureTableStorage -Pre
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>     + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
>     + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
>  
> Time Elapsed: 00:00:02.9097371

**Comment by liamdawson** [comment] 2017-06-26 23:27
Try adding a `<PackageTargetFallback>$(PackageTargetFallback); portable-net40+sl5+win8+wp8+wpa81</PackageTargetFallback>` into the first `<ItemGroup>` in your `csproj` file.

**Comment by WolfyUK** [comment] 2017-07-04 11:43
@liamdawson I think you mean the first `<PropertyGroup>`. That worked for me.

**Comment by siewers** [comment] 2017-08-18 08:49
I believe this issue can be resolved by upgrading the dependencies on the `WindowsAzure.Storage` package. I installed the latest version from NuGet, which seems to be compatible with this package.

**Comment by Structed** [comment] 2018-10-18 14:41
> 
> 
> I believe this issue can be resolved by upgrading the dependencies on the `WindowsAzure.Storage` package. I installed the latest version from NuGet, which seems to be compatible with this package.

I can confirm that `serilog.sinks.azuretablestorage` 4.0.0 in combination with `WindowsAzure.Storage` 9.3.1 works just fine - on both .NET Core 1.1 and 2.1

**Comment by petrastrucic** [comment] 2018-12-12 13:20
I had the same problem. Resolved as suggested by @Structed and in an addition to his statement, it works with WindowsAzure.Storage 9.3.3 too.

**Comment by Structed** [comment] 2018-12-14 13:10
So the dependency version needs an upgrade to a compatible version, right?

**Closed** 2022-05-14 03:17 UTC
