### ISSUE TITLE
After upgrade >= 8.0.35 the sink stopped sending logs to azure. (I use custom IKeyGenerator)

### ISSUE THREAD

**Issue by krstan4o** [serilog-contrib/serilog-sinks-azuretablestorage#97] opened 2023-06-26 00:23 UTC
**Description**
After upgrade the sink stopped sending logs to azure. (I use custom IKeyGenerator)

**Reproduction**
secrets.json:

"Serilog:Using:0": "Serilog.Sinks.AzureTableStorage",
"Serilog:WriteTo:0:Name": "AzureTableStorageWithProperties",
"Serilog:WriteTo:0:Args:storageTableName": "Logs",
"Serilog:WriteTo:0:Args:connectionString": "DefaultEndpointsProtocol=https;AccountName=mystorageaccount;AccountKey=myaccountkey==;EndpointSuffix=core.windows.net",
"Serilog:WriteTo:0:Args:keyGenerator": "MyProject.Loggers.Serilog.AzureKeyGenerator, MyProject.Loggers",

Program.cs:

.UseSerilog((ctx, config) =>
                {
                    config.ReadFrom.Configuration(ctx.Configuration);
                });

**Expected behavior**
To Find Logs in Azure table.

**Relevant package, tooling and runtime versions**
System: Win 11 Pro Version	10.0.22621 Build 22621
Project: <TargetFramework>net6.0</TargetFramework>
Packages: Affected with bug: Serilog.Sinks.AzureTableStorage >= 8.0.35 (Working version is: 7.0.25)

**Additional context**
Difference we find -> is the moved interface for: IKeyGenerator:

In versions < 8.0.35 its in: Serilog.Sinks.AzureTableStorage.KeyGenerator.IKeyGenerator
but versions >= 8.0.35 its in: Serilog.Sinks.AzureTableStorage.IKeyGenerator

Also the requirements of implemented methods for this interface is different.

**Comment by codin-dev** [comment] 2023-06-26 07:40
You should now use AzureTableStorage instead of AzureTableStorageWithProperties

**Comment by krstan4o** [comment] 2023-06-26 09:16
Changed but now i see only one row written in parralel i have console sink witch has a lot of logs and same logs needs to go to azure table also:

[12:13:21 INF Microsoft.Hosting.Lifetime] Now listening on: https://localhost:44373
[12:13:21 DBG Microsoft.AspNetCore.Hosting.Diagnostics] Loaded hosting startup assembly Bgf.Web
[12:13:21 DBG Microsoft.AspNetCore.Hosting.Diagnostics] Loaded hosting startup assembly Microsoft.AspNetCore.Watch.BrowserRefresh
[12:13:21 DBG Microsoft.AspNetCore.Hosting.Diagnostics] Loaded hosting startup assembly Microsoft.WebTools.BrowserLink.Net
[12:13:21 INF Microsoft.Hosting.Lifetime] Application started. Press Ctrl+C to shut down.
[12:13:21 INF Microsoft.Hosting.Lifetime] Hosting environment: Development
[12:13:21 INF Microsoft.Hosting.Lifetime] Content root path: D:\AzureDevOps\Loop\loop.api\Web\Bgf.Web
[12:13:21 DBG Microsoft.Extensions.Hosting.Internal.Host] Hosting started


Config: 

  "Serilog:Using:0": "Serilog.Sinks.Console",
  "Serilog:WriteTo:0:Name": "Console",
  "Serilog:WriteTo:0:Args:outputTemplate": "[{Timestamp:HH:mm:ss} {Level:u3} {SourceContext}] {Message:lj}{NewLine}{Exception}",
  
  "Serilog:Using:1": "Serilog.Sinks.AzureTableStorage",
  "Serilog:WriteTo:1:Name": "AzureTableStorage",
  "Serilog:WriteTo:1:Args:storageTableName": "MyLogTable",
  "Serilog:WriteTo:1:Args:connectionString": "myConStr",
  "Serilog:WriteTo:1:Args:keyGenerator": "MyLoggers.Loggers.Serilog.AzureKeyGenerator, MyLoggers.Loggers",

  "Serilog:MinimumLevel:Default": "Verbose",
  "Serilog:MinimumLevel:Override:Default": "Verbose",
  "Serilog:MinimumLevel:Override:Microsoft": "Verbose",
  "Serilog:MinimumLevel:Override:Bgf": "Verbose",
  "Serilog:MinimumLevel:Override:Bgf.Web.API.Controllers.LoopController": "Verbose",
  "Serilog:MinimumLevel:Override:Microsoft.EntityFrameworkCore.Database.Command": "Verbose",
  
  "Serilog:Enrich:2": "WithExceptionDetails",
  "Serilog:Enrich:1": "WithMachineName",
  "Serilog:Enrich:0": "FromLogContext",

**Comment by codin-dev** [comment] 2023-06-26 10:12
From the custom key generator class, did you remove the suffix argument, from GenerateRowKey method?

**Comment by krstan4o** [comment] 2023-06-26 11:29
Yes it is removed.

**Comment by RoryMcCrossan** [comment] 2023-07-03 20:52
Also seeing this same problem (#98). I raised a new bug report, but the issue is identical to this. Downgrading to 7.0.25 fixes the issue and using a custom IKeyLogger implementation works once more.

**Comment by pwelter34** [comment] 2023-08-01 14:32
the issue was you need a public parameterless constructor for the type specified in configuration. Version 9 updates the default implementations to support this requirement better. It is a minor breaking change however.

**Comment by RoryMcCrossan** [comment] 2023-08-12 15:34
I appreciate your efforts, but please be aware that the problem has not been resolved in v9.0.0. 
I have upgraded the library via Nuget, cleaned and rebuilt the solution, and updated the namespace in use to reference IKeyGenerator, as is now required. I get the EXACT same behaviour as originally outlined above.

Once more, the only way I get consistent output to TableStorage is by downgrading to 7.0.25.

**Comment by krstan4o** [comment] 2023-08-12 21:04
Yes i confirm the last comment

Also "the issue was you need a public parameterless constructor" => I already have public parameterless constructor

**Comment by pwelter34** [comment] 2023-08-13 16:45
could you give me more details to troubleshoot the issue?  

@RoryMcCrossan what do you mean by IKeyGenerator is now required?  what is the configuration you are using?

could you setup debug logger to see if there are any errors?

https://github.com/serilog/serilog/wiki/Debugging-and-Diagnostics

thanks,
~ Paul

**Comment by krstan4o** [comment] 2023-08-22 00:55
with 9.0.0 and empty constructor inside the IKeyGenerator it works

Also the setting:

"Serilog:WriteTo:1:Name": "AzureTableStorageWithProperties"

needs to be:

"Serilog:WriteTo:1:Name": "AzureTableStorage"

if using 9.0.0

**Comment by pwelter34** [comment] 2024-03-28 14:05
closed due to no activity

**Closed by pwelter34** 2024-03-28 14:05 UTC
Labels: bug
