### ISSUE TITLE
Constant POST requests to https://<account>.table.core.windows.net:443/Tables() failing with 409

### ISSUE THREAD

**Issue by adrianbontea** [serilog-contrib/serilog-sinks-azuretablestorage#42] opened 2018-03-08 18:57 UTC
Hi,

We are using the `Serilog.Sinks.AzureTableStorage` v4.0.0 for logging from a web app running on .net framework 4.6.1, hosted in Azure as an App Service. Logging is currently the only thing in the system that writes to Azure Table Storage.

During high traffic periods where a lot of log entries are produced we are seeing (logged as Dependency Call Failures in Azure App Insights) a very high rate of POST requests to `https://<account>.table.core.windows.net:443/Tables()` that fail with 409 from the Azure Table Service API.

The log entries that the application produces accumulate normally under the `LogEventEntity` table.

What could be the source of these requests? Does the AzureTableStorage sink implement some kind of health check mechanism that could be doing this kind of requests? (That seem invalid)

Thanks,
Adrian

**Comment by cdavid** [comment] 2018-03-21 16:40
Hi @adrianbontea 

409 is the status code for conflict (as per [here](https://stackoverflow.com/questions/21918898/azure-table-duplicate-partition-key-results-in-409-conflict)). Azure Table Storage gets back a conflict when the (Partition Key, Row Key) pair is identical to another row in the table.

Can you please give us some more details about how you use this sink (in particular, how and if you generate your own partition / row keys)?

Catalin

**Comment by garthvh** [comment] 2018-12-28 21:11
We are seeing the same thing here @cdavid this is not happening on an insert, rather what appears to be the account table list query.

**Comment by garthvh** [comment] 2019-01-04 19:45
You can close the issue, this seems to be expected behavior for the client library 8+ CloudTable.CreateIfNotExists throws a 409 error and moves on if the table already exists.

**Comment by ThomasPe** [comment] 2022-05-04 12:35
I feel like we should address this by checking manually if the table already exists as outlined here: https://medium.com/medialesson/application-insights-azure-table-storage-createifnotexists-errors-3e2584a38b24

**Comment by ThomasPe** [comment] 2022-05-17 09:00
Fixed

**Closed by ThomasPe** 2022-05-17 09:00 UTC
